[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# compile deps with llvm still for runtime perf
[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",

    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]

rustdocflags = [
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
